. Sign in to your AWS account, and locate the Partner Solution on the https://aws.amazon.com/marketplace/pp/prodview-s56hvqbcyj5qe[AWS Marketplace].
. Click the `Continue to Subscribe` button.
. Click the `Continue to Configuration` button.
. Ensure the most recent version of the software is selected and click Continue to Launch.
. Click the `Click to Launch Antivirus for Amazon S3 Deployment` link.
. The AWS CloudFormation console opens with a prepopulated template.
. Ensure you are deploying the Stack in the appropriate region.
. On the Quick create stack page, enter your desired Stack Name. 
. Review the parameters for the template and provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. 

[.info]
====
You must configure:
  
* The VPC in which to place the public-facing Console.
* Two subnets from within that VPC.  Ensure both allow outbound internet traffic.
* Console Security Group CIDR Block.
* Admin User Email Address for the Console management account.  Login credentials will be sent to this address.

Important optional parameters:
  
*Admin User Name
** This will be the initial user created for the console management website, with admin-level permissions.  If modifying the default value, ensure the name entered is three characters or greater.

* Agent Scanning Engine
** Choose the engine that should be used to scan files.  Please refer to the Marketplace listing for pricing differences.

* Multi-Engine Scanning Mode
** Choose how many engines you want to use to scan your files:
*** Disabled will use a single engine.
*** All will scan every file with both engines.
*** LargeFiles will scan files larger than 2GB using the Sophos engine.

* Enable Large File Scanning
** If "Yes" is selected, an EC2 instance will be launched a file is found to be too large to be scanned by the normal agent.

* Extra Large File Disk Size
** Choose a larger disk size (between 20 - 16,300 GB) to enable scanning larger files, up to 5 GB fewer than the total disk size. 
** Note: This only applies when using the Sophos scanning engine with EC2 large file scanning enabled.

* Buckets to protect
** Note that this only works for buckets in the same region as this deployment.

* Existing Transfer Family Server
** If you do not have an existing Transfer Family Server, leave this option set to `No`, and a Transfer Family Server will automatically be deployed for you.

* Quick Start Disable Auto-Protect
** When set to `No`, the bucket which is created to store files uploaded to the Transfer Server is automatically protected by the Antivirus for Managed File Transfers Console. It is not recommended to change this default.
====
  
. Check the acknowledge that AWS CloudFormation might create IAM resources with custom names box.
. Check the scknowledge that CloudFormation might require the following capability: CAPABILITY_AUTO_EXPAND box.
. Choose Create stack. The stack takes between 5-15 minutes to deploy.
. Monitor the stack's status, and when the status is CREATE_COMPLETE, the deployment is ready.
. To view the created resources, choose the Outputs and Resources tabs.
