// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== {partner-product-short-name} console
After deployment, check the administrator email account for a message from `Antivirus for Amazon S3—Console Account Information`. It contains a link to the {partner-product-short-name} console and temporary login credentials.

Choose the link to the {partner-product-short-name} console in the email message and log in using the temporary credentials. After logging in, change your password as prompted and make changes to your console configuration as necessary.

For more information on getting started with {partner-product-short-name}, refer to https://help.cloudstoragesec.com/getting-started/initial-config[How to Configure^].

=== Transfer Family server
If you selected to deploy a Transfer Family server during deployment, sign in to the AWS Management Console and open the https://us-east-1.console.aws.amazon.com/transfer#/[AWS Transfer Family console^]. Review the default settings for the server deployed by the solution. Note the following:

* The server uses SFTP (Secure Shell File Transfer Protocol).
* The server has a public endpoint.
* The deployment creates a Lambda function to validate authentication for secure file transfers.
* The solution uploads files directly to S3 directly and invokes an event-based scan by Antivirus for Managed File Transfers.
* To connect to the server, use the same username and password configured in the Antivirus for Managed File Transfers console.
