AWSTemplateFormatVersion: 2010-09-09
Description: Version 1.00.000 - CloudFormation template for CloudStorageSec (CSS) Console software alongside a AWS TransferFamily deployment. (qs-1uc9a1c0k)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - UserName
          - Email
        Label:
          default: User Configuration
      - Parameters:
          - AvailabilityZones
          - VPCCIDR
          - Subnet1CIDR
          - Subnet2CIDR
          - ConsoleSecurityGroupCidrBlock
        Label:
          default: Network Configuration
      - Parameters:
          - AgentScanningEngine
          - MultiEngineScanningMode
          - AgentDiskSize
          - EnableLargeFileScanning
          - LargeFileDiskSize
          - BucketsToProtect
        Label:
          default: CSS Configuration
      - Parameters:
          - ExistingTransferFamilyServer
        Label:
          default: Transfer Family
      - Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
          - QSDisableAutoProtect
        Label:
          default: AWS Quick Start Configuration
    ParameterLabels:
      UserName:
        default: Admin User Name
      Email:
        default: Admin User Email Address
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: Virtual Private Cloud (VPC) CIDR Block
      Subnet1CIDR:
        default: Subnet 1 CIDR Block
      Subnet2CIDR:
        default: Subnet 2 CIDR Block
      ConsoleSecurityGroupCidrBlock:
        default: Console Security Group CIDR Block
      AgentScanningEngine:
        default: Agent Scanning Engine
      MultiEngineScanningMode:
        default: Multi-Engine Scanning Mode
      AgentDiskSize:
        default: Agent Disk Size
      EnableLargeFileScanning:
        default: Enable Large File Scanning
      LargeFileDiskSize:
        default: Extra Large File Disk Size
      ExistingTransferFamilyServer:
        default: Existing Transfer Family Server
      BucketsToProtect:
        default: Buckets to Protect
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSDisableAutoProtect:
        default: Quick Start Disable Auto-Protect
  cfn-lint:
    config:
      ignore_checks: [EIAMRoleResourceWildardPassRole]
Parameters:
  UserName:
    Type: String
    Description: Initial user name for the Console management website
    MinLength: 1
    MaxLength: 128
    Default: admin
  Email:
    Type: String
    Description: Email address for Console management website account
    AllowedPattern: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
    ConstraintDescription: Must be a valid email address.
  AvailabilityZones:
    Description: Availability Zones to use for the subnets in the VPC. Must choose exactly 2.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  Subnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the subnet located in Availability Zone 1.
    Type: String
  Subnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the subnet located in Availability Zone 2.
    Type: String
  ConsoleSecurityGroupCidrBlock:
    Type: String
    Description: The IP address range that can access the Console management website (e.g. X.X.X.X/32 for a single given IP, 0.0.0.0/0 for open access)
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ((\d{1,3})\.){3}\d{1,3}/\d{1,2}
    ConstraintDescription: Must be valid CIDR notation of the form X.X.X.X/X
  AgentScanningEngine:
    Type: String
    Default: "Sophos"
    AllowedValues: ["ClamAV", "Sophos"]
    Description: "Choose the engine that should be used to scan files (See Marketplace listing for pricing differences)"
  MultiEngineScanningMode:
    Type: String
    Default: "Disabled"
    AllowedValues: ["Disabled", "All", "LargeFiles"]
    Description: "Choose if you want to use multiple engines to scan files. All will scan every file with both engines, LargeFiles will scan files larger than 2GB with Sophos. Premium Engine pricing applies."
  AgentDiskSize:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 200
    Description: Choose a larger disk size (up to 200 GB) to enable scanning larger files, up to 5 GB fewer than the total disk size. This only applies when using the Sophos scanning engine.
  EnableLargeFileScanning:
    Type: String
    Default: "No"
    AllowedValues: ["Yes", "No"]
    Description: Pick Yes if you would like to have EC2 instances launched to scan files too large to be scanned by the normal agent
  LargeFileDiskSize:
    Type: Number
    Default: 2000
    MinValue: 20
    MaxValue: 16300
    Description: Choose a larger disk size (between 20 - 16,300 GB) to enable scanning larger files, up to 5 GB fewer than the total disk size. This only applies when using the Sophos scanning engine with EC2 large file scanning enabled.
  ExistingTransferFamilyServer:
    Type: String
    Default: "No"
    AllowedValues: ["Yes", "No"]
    Description: If you already have an existing Transfer Family server, and just want to deploy the Cloud Storage Security Console, choose "Yes".
  BucketsToProtect:
    Type: String
    Default: ""
    Description: Enter any pre-existing buckets that you would like to automatically enable event-based protection on. Bucket names must be separated by commas (e.g. bucket1,bucket2,bucket3). Protected buckets can be managed after deployment in the CSS Console.
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-\.]*[0-9a-zA-Z])*$'
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, periods, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: "Name of the S3 bucket for your copy of the Quick Start assets.
      Keep the default name unless you are customizing the template.
      Changing the name updates code references to point to a new Quick
      Start location. This name can include numbers, lowercase letters,
      uppercase letters, and hyphens, but do not start or end with a hyphen (-).
      See https://aws-quickstart.github.io/option1.html."
    Type: String
  QSS3BucketRegion:
    Default: us-east-1
    Description: "AWS Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. Keep the default Region unless you are customizing the template.
      Changing this Region updates code references to point to a new Quick Start location.
      When using your own bucket, specify the Region.
      See https://aws-quickstart.github.io/option1.html."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-cloud-storage-security-antivirus-for-amazon-s3/
    Description: "S3 key prefix that is used to simulate a directory for your copy of the
      Quick Start assets. Keep the default prefix unless you are customizing
      the template. Changing this prefix updates code references to point to
      a new Quick Start location. This prefix can include numbers, lowercase
      letters, uppercase letters, hyphens (-), and forward slashes (/).
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
      and https://aws-quickstart.github.io/option1.html."
    Type: String
  QSDisableAutoProtect:
    Type: String
    Default: "No"
    AllowedValues: ["Yes", "No"]
    Description: "By default, the bucket which is created to store files uploaded to the Transfer Server,
      is automatically protected by the CSS Console. It is highly recommended you keep the default value,
      in order to ensure all files uploaded are scanned for malware immediately."
Conditions:
  DeployTransferFamily: !Equals [!Ref ExistingTransferFamilyServer, "No"]
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, "aws-quickstart"]
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
        - S3Bucket: !If [UsingDefaultBucket, !Sub "aws-quickstart-${AWS::Region}", !Ref QSS3BucketName]
          S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
      Parameters:
        AvailabilityZones: !Join
          - ","
          - !Ref AvailabilityZones
        PublicSubnet1CIDR: !Ref Subnet1CIDR
        PublicSubnet2CIDR: !Ref Subnet2CIDR
        VPCCIDR: !Ref VPCCIDR
        CreateNATGateways: "false"
        CreatePrivateSubnets: "false"
  CssMftStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/css-mft.template.yaml
        - S3Bucket: !If [UsingDefaultBucket, !Sub "aws-quickstart-${AWS::Region}", !Ref QSS3BucketName]
          S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
      Parameters:
        UserName: !Ref UserName
        Email: !Ref Email
        VPC: !GetAtt VPCStack.Outputs.VPCID
        SubnetA: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        SubnetB: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        ConsoleSecurityGroupCidrBlock: !Ref ConsoleSecurityGroupCidrBlock
        AgentScanningEngine: !Ref AgentScanningEngine
        MultiEngineScanningMode: !Ref MultiEngineScanningMode
        AgentDiskSize: !Ref AgentDiskSize
        EnableLargeFileScanning: !Ref EnableLargeFileScanning
        LargeFileDiskSize: !Ref LargeFileDiskSize
        ExistingTransferFamilyServer: !Ref ExistingTransferFamilyServer
        BucketsToProtect: !Ref BucketsToProtect
        QSDisableAutoProtect: !Ref QSDisableAutoProtect
Outputs:
  TransferFamilyDestinationBucket:
    Condition: DeployTransferFamily
    Description: Name of the bucket created for storing files uploaded to the transfer family server
    Value: !GetAtt CssMftStack.Outputs.TransferFamilyDestinationBucket
    Export:
      Name: !Sub "${AWS::StackName}-TransferFamilyDestinationBucket"
  TransferFamilyServerId:
    Condition: DeployTransferFamily
    Description: ID of the Transfer Family server.
    Value: !GetAtt CssMftStack.Outputs.TransferFamilyServerId
    Export:
      Name: !Sub "${AWS::StackName}-TransferFamilyServer"
  TransferFamilyPublicEndpoint:
    Condition: DeployTransferFamily
    Description: Public VPC endpoint for the Transfer Family AS2 server.
    Value: !GetAtt CssMftStack.Outputs.TransferFamilyPublicEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-TransferFamilyPublicEndpoint"
  ConsoleWebAddress:
    Description: Public DNS address of Console Web Interface
    Value: !GetAtt CssMftStack.Outputs.ConsoleWebAddress
  UserName:
    Description: User Name used to log in to console
    Value: !GetAtt CssMftStack.Outputs.UserName
  Password:
    Description: Temporary password used to log in to console
    Value: !GetAtt CssMftStack.Outputs.Password
  ProactiveNotificationsTopicArn:
    Description: ARN for the proactive notifications topic
    Value: !GetAtt CssMftStack.Outputs.ProactiveNotificationsTopicArn
    Export:
      Name: !Sub "${AWS::StackName}-proactive-notifications-sns-topic"
  CSSConsoleStackTemplateURL:
    Description: CFT used for deploying the CSS Console
    Value: !GetAtt CssMftStack.Outputs.CSSConsoleStackTemplateURL
